# Generated by Django 4.2.6 on 2023-10-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('work_experience', models.TextField()),
                ('references', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.department')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=1500)),
                ('CompanyName', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('MinGPA', models.FloatField()),
                ('DeadLine', models.DateField()),
                ('Departments', models.ManyToManyField(related_name='eligible_companies', to='pages.department')),
            ],
        ),
    ]
