# Generated by Django 4.2.6 on 2023-10-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default=True, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='details',
            field=models.TextField(),
        ),
    ]
