# Generated by Django 4.2.6 on 2023-10-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_student_user_alter_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='education',
        ),
        migrations.RemoveField(
            model_name='student',
            name='references',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='student',
            name='HSC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='SSLC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gctmail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='isLatral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='rollnum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
