# Generated by Django 4.2.6 on 2023-10-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_student_education_remove_student_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bannerUrl',
            field=models.CharField(default='https://u-static.fotor.com/images/text-to-image/result/PRO-31d0bb5520b84354b1a2f395521b6a20.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='profileUrl',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/1999/1999625.png', max_length=200),
        ),
    ]
