# Generated by Django 4.2.6 on 2023-10-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_student_bannerurl_student_profileurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
