# Generated by Django 4.2.6 on 2023-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_company_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
