# Generated by Django 4.2.6 on 2023-10-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_company_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isPlaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='placedIn',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.company'),
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.student')),
            ],
        ),
    ]
