# Generated by Django 4.2.6 on 2023-10-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_student_isplaced_student_placedin_studentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='placedIn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.company'),
        ),
    ]
