# Generated by Django 4.2.6 on 2023-10-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_application_company_dualplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.company'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.student'),
        ),
    ]
