# Generated by Django 4.2.6 on 2023-10-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_application_company_alter_application_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='DeadLine',
            field=models.DateTimeField(),
        ),
    ]
