# Generated by Django 4.2.6 on 2023-10-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_company_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='MinGPAHSC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='MinSSLC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
